### ISSUE TITLE
Failover protocol support

### ISSUE THREAD

**Issue by adriana-cass-visma** [DaveSenn/Stomp.Net#7]
Hello,

Are you planning to support ActiveMQ failover protocol scheme?

Thank you,
Adriana

**Comment by DaveSenn** [comment]
It is an interesting idea. But at the moment I don’t have the time to implement this feature. If you like you can submit a pull request I would happily accept it.

You can also use the ExceptionListener event of IConnection to detect broken connections and implement your own reconnect/failover logic.

Otherwise you could take a look at the Apache NMS library http://activemq.apache.org/nms/apachenmsstomp.html (STOMP.Net is stripped down version of that library with a few changes required to work with non MQ brokers). I think NMS supports failover connections.

I hope this helps you.

Best regards
Dave
